---
- name: sshd
  hosts: all
  become: true
  tasks:
    - name: sshd
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^# banner" 
        line: "banner /etc/motd" 
    - name: sshd
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#X11Forwarding' 
        line: 'X11Forwarding no' 
    - name: sshd
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries' 
        line: 'MaxAuthTries 3' 

#banner is set to /etc/motd
#X11Forwarding is disabled
#MaxAuthTries is set to 3
    
